platform :ios, "8.0"

use_frameworks!
pod 'Alamofire'
pod 'ChameleonFramework'
pod 'KVNProgress'
pod 'JDStatusBarNotification'
pod 'DZNEmptyDataSet'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
pod 'TextFieldEffects'
